### PR TITLE
Using sed instead of tr  fixed #7

### LINKED ISSUE #7: Encoding issue or broken sed command
screen shot 2016-02-08 at 1 45 13 pm

I tried many other fonts in my iTerm terminal. 

Interestingly, in Mac Terminal I get an error like this: 

```
sed: -e expression #1, char 211: unterminated `s' command
sed: -e expression #1, char 197: unterminated `s' command
```

### PR DESCRIPTION
**Pull request by aziz**
Thanks @noscript, see #7

### CODE REVIEW

**Comment by stevemao** [comment]
What is your npm name? I'll add you so you can push yourself.

**Comment by aziz** [comment]
it's the same as my github username: `aziz`

**Comment by aziz** [comment]
Bumped version and pushed to npm

**Comment by stevemao** [comment]
Thanks @aziz :)

**Comment by rjc** [comment]
I only just noticed that it's not a `-` character - should have read the **linked** issue.
Sorry for the noise.

**Pull request merged**
