### PR TITLE
prefer a global diff-highlight, but fallback to our local copy

### LINKED ISSUE #6: Hard dependency on diff-highlight from diff-so-fancy
Maybe we should just depend on `diff-highlight` from inside of `diff-so-fancy`.

That would mean people instead configure it with `git diff | diff-so-fancy` directly.

If `diff-highlight` isn't found, we could just pass through the `stdin` and perhaps issue a warning that says "hey you're missing diff-highlight bud"

Seems a little more user-friendly. wdyt?

### PR DESCRIPTION
**Pull request by paulirish**
This builds on the discussion in #29 and fixes #6.
All the context is there.

It also fixes a small bug in @anshul's pr #36 . :)

### CODE REVIEW

**Comment by stevemao** [comment]
Should it prefer global? I was thinking:

1. find our local hard dependency, if not found
2. find global dependency (may not be our hard dependency), if not found
3, throw error

Dependency needs to be executable.

**Comment by bquorning** [comment]
:+1: Thank you. #36 broke diff-so-fancy for me, and this PR fixes it again.

**Comment by paulirish** [comment]
Cool. Steve, I'm fine with s follow-up commit to swap the order

**Comment by anshul** [comment]
Oops.  @paulirish Thanks for fixing.

**Comment by stevemao** [comment]
Oh well only you think it's better @paulirish :)

**Comment by paulirish** [comment]
I don't have a strong feeling on the order

**Comment by stevemao** [comment]
Cool. Don't worry about it then.

**Pull request merged**
