### PR TITLE
2 1-digit ansi instead of 1 3-digit for dim magenta

### LINKED ISSUE #17: Incorrectly highlighted lines on Windows
I've set up the tool using the instructions from the README (npm install, then set core.pager value). I've run a test diff and the *first code line of each file* is incorrectly highlighted and colored:

capture

Also, the headers are white instead of yellow, but that's a minor issue.

My environment: Windows 10, Cmder console (but issue also occurs in PowerShell), default Git for Windows installer.

### PR DESCRIPTION
**Pull request by stevemao**
Hopefully this is more supported.
Fixes #17

### CODE REVIEW

**Comment by paulirish** [comment]
Yeah I like this. works for me

**Comment by paulirish** [comment]
It is a little weird to have the foreground color totally match the diff annotation though:
image

Can we tweak the foreground in another way?

**Comment by stevemao** [comment]
That's because iterm doesn't support "dim" (`\x1B\[2m`) (it's supported in the nightly). Open the default terminal you'll see it.

**Comment by paulirish** [comment]
chill:

image


🍦

**Comment by tleunen** [comment]
Not sure the color is great... We can barely see what's written :/

**Pull request merged**
